package yf.liu.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTfFProductattach<M extends BaseTfFProductattach<M>> extends Model<M> implements IBean {

	public void setPkid(java.math.BigDecimal pkid) {
		set("pkid", pkid);
	}

	public java.math.BigDecimal getPkid() {
		return get("pkid");
	}

	public void setAttachRootId(java.lang.String attachRootId) {
		set("ATTACH_ROOT_ID", attachRootId);
	}

	public java.lang.String getAttachRootId() {
		return get("ATTACH_ROOT_ID");
	}

	public void setAttachName(java.lang.String attachName) {
		set("ATTACH_NAME", attachName);
	}

	public java.lang.String getAttachName() {
		return get("ATTACH_NAME");
	}

	public void setFileType(java.lang.Integer fileType) {
		set("FILE_TYPE", fileType);
	}

	public java.lang.Integer getFileType() {
		return get("FILE_TYPE");
	}

	public void setFilePath(java.lang.String filePath) {
		set("FILE_PATH", filePath);
	}

	public java.lang.String getFilePath() {
		return get("FILE_PATH");
	}

	public void setAttachDesc(java.lang.String attachDesc) {
		set("ATTACH_DESC", attachDesc);
	}

	public java.lang.String getAttachDesc() {
		return get("ATTACH_DESC");
	}

	public void setVALIDITY(java.lang.String VALIDITY) {
		set("VALIDITY", VALIDITY);
	}

	public java.lang.String getVALIDITY() {
		return get("VALIDITY");
	}

	public void setCustId(java.lang.String custId) {
		set("CUST_ID", custId);
	}

	public java.lang.String getCustId() {
		return get("CUST_ID");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setRsrvStr1(java.lang.String rsrvStr1) {
		set("RSRV_STR1", rsrvStr1);
	}

	public java.lang.String getRsrvStr1() {
		return get("RSRV_STR1");
	}

	public void setRsrvStr2(java.lang.String rsrvStr2) {
		set("RSRV_STR2", rsrvStr2);
	}

	public java.lang.String getRsrvStr2() {
		return get("RSRV_STR2");
	}

	public void setRsrvStr3(java.lang.String rsrvStr3) {
		set("RSRV_STR3", rsrvStr3);
	}

	public java.lang.String getRsrvStr3() {
		return get("RSRV_STR3");
	}

	public void setRsrvNum4(java.lang.Float rsrvNum4) {
		set("RSRV_NUM4", rsrvNum4);
	}

	public java.lang.Float getRsrvNum4() {
		return get("RSRV_NUM4");
	}

	public void setRsrvNum5(java.lang.Float rsrvNum5) {
		set("RSRV_NUM5", rsrvNum5);
	}

	public java.lang.Float getRsrvNum5() {
		return get("RSRV_NUM5");
	}

	public void setRsrvStr6(java.lang.String rsrvStr6) {
		set("RSRV_STR6", rsrvStr6);
	}

	public java.lang.String getRsrvStr6() {
		return get("RSRV_STR6");
	}

	public void setRsrvStr7(java.lang.String rsrvStr7) {
		set("RSRV_STR7", rsrvStr7);
	}

	public java.lang.String getRsrvStr7() {
		return get("RSRV_STR7");
	}

	public void setRsrvStr8(java.lang.String rsrvStr8) {
		set("RSRV_STR8", rsrvStr8);
	}

	public java.lang.String getRsrvStr8() {
		return get("RSRV_STR8");
	}

	public void setRsrvStr9(java.lang.String rsrvStr9) {
		set("RSRV_STR9", rsrvStr9);
	}

	public java.lang.String getRsrvStr9() {
		return get("RSRV_STR9");
	}

	public void setRsrvStr10(java.lang.String rsrvStr10) {
		set("RSRV_STR10", rsrvStr10);
	}

	public java.lang.String getRsrvStr10() {
		return get("RSRV_STR10");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

	public void setInDate(java.util.Date inDate) {
		set("IN_DATE", inDate);
	}

	public java.util.Date getInDate() {
		return get("IN_DATE");
	}

	public void setAttachId(java.lang.Integer attachId) {
		set("attach_id", attachId);
	}

	public java.lang.Integer getAttachId() {
		return get("attach_id");
	}

	public void setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
	}

	public java.lang.Integer getOrderby() {
		return get("orderby");
	}

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setImages(byte[] Images) {
		set("Images", Images);
	}

	public byte[] getImages() {
		return get("Images");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setMemo1(java.lang.String memo1) {
		set("memo1", memo1);
	}

	public java.lang.String getMemo1() {
		return get("memo1");
	}

	public void setMemo3(java.lang.String memo3) {
		set("memo3", memo3);
	}

	public java.lang.String getMemo3() {
		return get("memo3");
	}

	public void setMemo4(java.lang.String memo4) {
		set("memo4", memo4);
	}

	public java.lang.String getMemo4() {
		return get("memo4");
	}

	public void setMemo5(java.lang.String memo5) {
		set("memo5", memo5);
	}

	public java.lang.String getMemo5() {
		return get("memo5");
	}

	public void setImagesid(java.lang.Integer Imagesid) {
		set("Imagesid", Imagesid);
	}

	public java.lang.Integer getImagesid() {
		return get("Imagesid");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setDelflag(java.lang.Integer delflag) {
		set("delflag", delflag);
	}

	public java.lang.Integer getDelflag() {
		return get("delflag");
	}

}
